"""empty message

Revision ID: 246bf2cf9430
Revises: 
Create Date: 2019-05-30 13:03:40.891893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246bf2cf9430'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_name', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('friends_count', sa.Integer(), nullable=False),
    sa.Column('profile_created_at', sa.DateTime(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=20), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name')
    )
    op.create_index(op.f('ix_users_profile_created_at'), 'users', ['profile_created_at'], unique=False)
    op.create_table('tweet',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('tweet_text', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hashtag_usage',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.tweet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag_usage')
    op.drop_table('tweet')
    op.drop_index(op.f('ix_users_profile_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
