"""empty message

Revision ID: 6c88f67d4726
Revises: 246bf2cf9430
Create Date: 2019-05-30 21:14:11.728720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c88f67d4726'
down_revision = '246bf2cf9430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###
