"""empty message

Revision ID: 83a1d7941458
Revises: 6c88f67d4726
Create Date: 2019-05-30 21:29:51.938604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a1d7941458'
down_revision = '6c88f67d4726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url')
    # ### end Alembic commands ###
