"""empty message

Revision ID: e4e84a1e4025
Revises: a789fe99bc7a
Create Date: 2019-05-27 18:45:21.437290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e84a1e4025'
down_revision = 'a789fe99bc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hashtag_usage', 'hashtag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hashtag_usage', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hashtag_usage', 'created_at')
    op.drop_column('hashtag_usage', 'id')
    op.drop_column('hashtag_usage', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtag_usage', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('hashtag_usage', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('hashtag_usage', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.alter_column('hashtag_usage', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hashtag_usage', 'hashtag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
