"""empty message

Revision ID: e7a6c5a9666b
Revises: f0aa406d13a5
Create Date: 2019-05-27 17:22:34.776044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a6c5a9666b'
down_revision = 'f0aa406d13a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtag_usage', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('hashtag_usage', 'hashtag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hashtag_usage', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hashtag_usage', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hashtag_usage', 'hashtag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('hashtag_usage', 'updated_at')
    op.drop_column('hashtag_usage', 'id')
    op.drop_column('hashtag_usage', 'created_at')
    # ### end Alembic commands ###
