"""empty message

Revision ID: f7c73c0aa69b
Revises: a789fe99bc7a
Create Date: 2019-05-28 15:06:08.871081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c73c0aa69b'
down_revision = 'a789fe99bc7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tweet_text', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hashtag', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('hashtag_usage', sa.Column('tweet_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'hashtag_usage', type_='foreignkey')
    op.create_foreign_key(None, 'hashtag_usage', 'tweet', ['tweet_id'], ['id'])
    op.create_foreign_key(None, 'hashtag_usage', 'hashtag', ['hashtag_id'], ['id'])
    op.drop_column('hashtag_usage', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashtag_usage', sa.Column('users_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'hashtag_usage', type_='foreignkey')
    op.drop_constraint(None, 'hashtag_usage', type_='foreignkey')
    op.create_foreign_key(None, 'hashtag_usage', 'users', ['users_id'], ['id'])
    op.drop_column('hashtag_usage', 'tweet_id')
    op.drop_column('hashtag', 'count')
    op.drop_table('tweet')
    # ### end Alembic commands ###
